Update README.md
Fix extra c in `scanner.c`
It also seems I need to add `-I./` to avoid:
```
scanner.c:5:10: fatal error: tree_sitter/parser.h: No such file or directory
    5 | #include <tree_sitter/parser.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```